(function(){
const BANK=window.SAA_MOCK_BANK||[];
const DOMAIN_NAMES={1:'Secure architectures',2:'Resilient architectures',3:'High-performing architectures',4:'Cost-optimized architectures'};
const CONFIGS={
 warmup:{name:'10-question warm-up',count:10,minutes:18,seed:41,kind:'WARM-UP',counts:{1:3,2:3,3:2,4:2}},
 diagnostic:{name:'20-question readiness check',count:20,minutes:40,seed:719,kind:'DIAGNOSTIC',counts:{1:6,2:5,3:5,4:4}},
 a:{name:'Mock Exam A',count:65,minutes:130,seed:103,kind:'FULL MOCK EXAM',counts:{1:20,2:17,3:15,4:13}},
 b:{name:'Mock Exam B',count:65,minutes:130,seed:307,kind:'FULL MOCK EXAM',counts:{1:20,2:17,3:15,4:13}},
 c:{name:'Mock Exam C',count:65,minutes:130,seed:911,kind:'FULL MOCK EXAM',counts:{1:20,2:17,3:15,4:13}},
 secure:{name:'Secure architectures drill',count:15,minutes:28,seed:1201,kind:'DOMAIN DRILL',counts:{1:15}},
 resilient:{name:'Resilient architectures drill',count:15,minutes:28,seed:1409,kind:'DOMAIN DRILL',counts:{2:15}},
 performance:{name:'High-performing architectures drill',count:15,minutes:28,seed:1601,kind:'DOMAIN DRILL',counts:{3:15}},
 cost:{name:'Cost-optimized architectures drill',count:15,minutes:28,seed:1801,kind:'DOMAIN DRILL',counts:{4:15}}
};
const $=id=>document.getElementById(id);let state=null,timerHandle=null;
function safeSet(k,v){try{localStorage.setItem(k,v)}catch(e){}}
function safeGet(k,d=''){try{return localStorage.getItem(k)||d}catch(e){return d}}
function safeRemove(k){try{localStorage.removeItem(k)}catch(e){}}
function rng(seed){return function(){seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function seededShuffle(items,seed){const a=[...items],r=rng(seed);for(let i=a.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function makeExam(key){const c=CONFIGS[key],picked=[];Object.entries(c.counts).forEach(([d,n])=>picked.push(...seededShuffle(BANK.filter(q=>q.d===+d),c.seed+(+d*97)).slice(0,n)));return seededShuffle(picked,c.seed+991)}
function formatTime(s){s=Math.max(0,s);return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function saveState(){if(state){state.savedAt=Date.now();safeSet('aws-saa-mock-current',JSON.stringify(state))}}
function clearState(){safeRemove('aws-saa-mock-current')}
function startExam(key,resume=null){const cfg=CONFIGS[key];state=resume||{key,questions:makeExam(key),answers:{},flags:[],pos:0,seconds:cfg.minutes*60,startedAt:Date.now()};$('examPicker').hidden=true;$('historyCard').hidden=true;$('examResults').hidden=true;$('examRunner').hidden=false;$('examTitle').textContent=cfg.name;$('examKind').textContent=cfg.kind;$('totalQuestions').textContent=state.questions.length;renderQuestion();startTimer();saveState();window.scrollTo({top:0,behavior:'smooth'})}
function startTimer(){clearInterval(timerHandle);$('timer').textContent=formatTime(state.seconds);timerHandle=setInterval(()=>{state.seconds--;$('timer').textContent=formatTime(state.seconds);if(state.seconds%15===0)saveState();if(state.seconds<=0){clearInterval(timerHandle);finishExam(true)}},1000)}
function selectedFor(i){return state.answers[i]||[]}
function renderQuestion(){const i=state.pos,q=state.questions[i],selected=selectedFor(i);$('currentNumber').textContent=i+1;$('questionDomain').textContent=`Domain ${q.d} · ${DOMAIN_NAMES[q.d]}`;$('questionText').textContent=q.q;$('selectionHint').textContent=q.c.length>1?`Select ${q.c.length} answers.`:'Select one answer.';$('flagButton').classList.toggle('active',state.flags.includes(i));$('flagButton').textContent=state.flags.includes(i)?'★ Flagged for review':'☆ Flag for review';$('examAnswers').innerHTML=q.a.map((a,idx)=>`<button type="button" class="exam-answer ${selected.includes(idx)?'selected':''}" data-answer="${idx}"><span>${String.fromCharCode(65+idx)}</span><b>${a}</b></button>`).join('');document.querySelectorAll('.exam-answer').forEach(btn=>btn.onclick=()=>choose(+btn.dataset.answer));$('previousQuestion').disabled=i===0;$('nextQuestion').textContent=i===state.questions.length-1?'Review & submit →':'Next →';paintNavigator();saveState()}
function choose(idx){const q=state.questions[state.pos];let a=selectedFor(state.pos);if(q.c.length===1)a=[idx];else if(a.includes(idx))a=a.filter(x=>x!==idx);else if(a.length<q.c.length)a=[...a,idx];else a=[...a.slice(1),idx];state.answers[state.pos]=a;renderQuestion()}
function paintNavigator(){const answered=Object.values(state.answers).filter(a=>a.length).length;$('answeredCount').textContent=answered;$('flaggedCount').textContent=state.flags.length;$('questionGrid').innerHTML=state.questions.map((_,i)=>`<button type="button" class="question-number ${i===state.pos?'current':''} ${selectedFor(i).length?'answered':''} ${state.flags.includes(i)?'flagged':''}" data-q="${i}">${i+1}</button>`).join('');document.querySelectorAll('.question-number').forEach(b=>b.onclick=()=>{state.pos=+b.dataset.q;renderQuestion()})}
function arraysEqual(a,b){return a.length===b.length&&[...a].sort().every((v,i)=>v===[...b].sort()[i])}
function finishExam(auto=false){if(!auto){const unanswered=state.questions.length-Object.values(state.answers).filter(a=>a.length).length;if(!confirm(unanswered?`Submit now? ${unanswered} questions are unanswered.`:'Submit this exam now?'))return}clearInterval(timerHandle);const cfg=CONFIGS[state.key],results=state.questions.map((q,i)=>({q,index:i,selected:selectedFor(i),correct:arraysEqual(selectedFor(i),q.c),flagged:state.flags.includes(i)}));const correct=results.filter(x=>x.correct).length,pct=Math.round(correct/results.length*100),elapsed=cfg.minutes*60-state.seconds;const domainStats={};results.forEach(r=>{domainStats[r.q.d]||={ok:0,total:0};domainStats[r.q.d].total++;if(r.correct)domainStats[r.q.d].ok++});const attempt={name:cfg.name,date:new Date().toISOString(),correct,total:results.length,pct,seconds:elapsed,domains:domainStats};let history=getHistory();history.unshift(attempt);safeSet('aws-saa-mock-history',JSON.stringify(history.slice(0,20)));clearState();state.results=results;$('examRunner').hidden=true;$('examResults').hidden=false;$('resultPercent').textContent=pct+'%';$('resultRing').style.setProperty('--score',pct+'%');$('resultTitle').textContent=pct>=80?'Strong practice result':pct>=70?'Close—review weak domains':'More review recommended';$('resultSummary').textContent=`${correct} of ${results.length} correct · ${formatTime(elapsed)} used. This is a raw study percentage, not an AWS scaled score.`;$('domainResults').innerHTML=Object.entries(domainStats).map(([d,s])=>{const p=Math.round(s.ok/s.total*100);return `<article><small>DOMAIN ${d}</small><b>${p}%</b><span>${s.ok}/${s.total} correct</span><i><em style="width:${p}%"></em></i><p>${DOMAIN_NAMES[d]}</p></article>`}).join('');$('reviewFilter').value='wrong';renderReview();paintHistory();window.scrollTo({top:0,behavior:'smooth'})}
function renderReview(){const filter=$('reviewFilter').value,items=state.results.filter(r=>filter==='all'||filter==='flagged'&&r.flagged||filter==='wrong'&&!r.correct);$('reviewList').innerHTML=items.length?items.map(r=>{const answerText=r.selected.length?r.selected.map(i=>`${String.fromCharCode(65+i)}. ${r.q.a[i]}`).join('<br>'):'No answer';const correctText=r.q.c.map(i=>`${String.fromCharCode(65+i)}. ${r.q.a[i]}`).join('<br>');return `<article class="review-card ${r.correct?'review-correct':'review-wrong'}"><div class="review-top"><span>Question ${r.index+1} · Domain ${r.q.d}</span><b>${r.correct?'Correct':'Review'}</b></div><h3>${r.q.q}</h3><div class="review-comparison"><div><small>YOUR ANSWER</small><p>${answerText}</p></div><div><small>CORRECT ANSWER</small><p>${correctText}</p></div></div><div class="review-explanation"><b>Why:</b> ${r.q.e}</div></article>`}).join(''):'<div class="empty-review">No questions match this filter.</div>'}
function getHistory(){try{return JSON.parse(safeGet('aws-saa-mock-history','[]'))}catch(e){return[]}}
function paintHistory(){const h=getHistory();$('historyList').innerHTML=h.length?h.map(x=>`<div class="history-row"><span><b>${x.name}</b><small>${new Date(x.date).toLocaleString()}</small></span><span><b>${x.pct}%</b><small>${x.correct}/${x.total} · ${formatTime(x.seconds)}</small></span></div>`).join(''):'<div class="empty-review">No completed attempts yet.</div>'}
function showPicker(){clearInterval(timerHandle);state=null;$('examResults').hidden=true;$('examRunner').hidden=true;$('examPicker').hidden=false;$('historyCard').hidden=false;paintHistory();window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.exam-option').forEach(b=>b.onclick=()=>startExam(b.dataset.exam));$('previousQuestion').onclick=()=>{if(state.pos>0){state.pos--;renderQuestion()}};$('nextQuestion').onclick=()=>{if(state.pos<state.questions.length-1){state.pos++;renderQuestion()}else finishExam(false)};$('flagButton').onclick=()=>{const i=state.pos;state.flags=state.flags.includes(i)?state.flags.filter(x=>x!==i):[...state.flags,i];renderQuestion()};$('submitExam').onclick=()=>finishExam(false);$('saveExit').onclick=()=>{saveState();showPicker();alert('Attempt saved in this browser. Reopen this page to resume it.')};$('returnPicker').onclick=showPicker;$('reviewWrong').onclick=()=>{$('reviewFilter').value='wrong';renderReview();document.querySelector('.review-section').scrollIntoView({behavior:'smooth'})};$('reviewFilter').onchange=renderReview;$('clearHistory').onclick=()=>{if(confirm('Clear saved mock-exam history?')){safeRemove('aws-saa-mock-history');paintHistory()}};paintHistory();
try{const saved=JSON.parse(safeGet('aws-saa-mock-current','null'));if(saved&&CONFIGS[saved.key]&&saved.questions?.length){const elapsed=Math.floor((Date.now()-(saved.savedAt||Date.now()))/1000);saved.seconds=Math.max(0,saved.seconds-elapsed);if(saved.seconds>0&&confirm(`Resume your saved ${CONFIGS[saved.key].name} attempt?`))startExam(saved.key,saved);else if(saved.seconds<=0){safeRemove('aws-saa-mock-current')}}}catch(e){}
})();
