(function(){
  const body=document.body,menu=document.getElementById('menuButton'),scrim=document.getElementById('sidebarScrim');
  if(menu)menu.addEventListener('click',()=>body.classList.toggle('sidebar-open'));if(scrim)scrim.addEventListener('click',()=>body.classList.remove('sidebar-open'));
  const key='aws-saa-study-lab-completed';const getDone=()=>{try{return JSON.parse(localStorage.getItem(key)||'[]')}catch(e){return[]}},saveDone=v=>localStorage.setItem(key,JSON.stringify(v));
  const page=(location.pathname.split('/').pop()||'index.html').toLowerCase(),complete=document.getElementById('completeLab');
  function paintComplete(){if(!complete)return;const done=getDone().includes(page);complete.classList.toggle('done',done);complete.querySelector('span:last-child').textContent=done?'Completed':'Mark complete'}
  if(complete){complete.addEventListener('click',()=>{let done=getDone();done=done.includes(page)?done.filter(x=>x!==page):[...done,page];saveDone(done);paintComplete()});paintComplete()}
  const tiles=[...document.querySelectorAll('.app-tile')],search=document.getElementById('labSearch')||document.getElementById('globalSearch'),global=document.getElementById('globalSearch');let domain='all';
  function filter(value=''){if(!tiles.length)return;const q=value.trim().toLowerCase();let visible=0;tiles.forEach(tile=>{const showText=!q||tile.textContent.toLowerCase().includes(q),showDomain=domain==='all'||tile.dataset.domain===domain,show=showText&&showDomain;tile.classList.toggle('is-hidden',!show);if(show)visible++});document.getElementById('emptySearch')?.classList.toggle('show',visible===0)}
  if(search)search.addEventListener('input',e=>filter(e.target.value));if(global&&global!==search)global.addEventListener('input',e=>filter(e.target.value));if(global&&!tiles.length)global.addEventListener('keydown',e=>{if(e.key==='Enter'&&global.value.trim())location.href='index.html?q='+encodeURIComponent(global.value.trim())});
  document.querySelectorAll('.domain-filter').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.domain-filter').forEach(x=>x.classList.remove('active'));btn.classList.add('active');domain=btn.dataset.filter;filter((document.getElementById('labSearch')||global)?.value||'')}));
  const initialQuery=new URLSearchParams(location.search).get('q');if(initialQuery&&tiles.length){const target=document.getElementById('labSearch')||global;if(target)target.value=initialQuery;filter(initialQuery)}
  if(tiles.length){const done=getDone(),completed=done.filter(x=>tiles.some(t=>t.dataset.page===x));tiles.forEach(t=>t.classList.toggle('completed',done.includes(t.dataset.page)));const pct=Math.round(completed.length/tiles.length*100);document.querySelectorAll('[data-progress]').forEach(el=>el.style.setProperty('--progress',pct+'%'));document.querySelectorAll('[data-progress-label]').forEach(el=>el.textContent=pct+'%');document.querySelectorAll('[data-complete-count]').forEach(el=>el.textContent=completed.length);document.querySelectorAll('[data-domain-card]').forEach(card=>{const d=card.dataset.domain,all=tiles.filter(t=>t.dataset.domain===d),count=all.filter(t=>done.includes(t.dataset.page)).length,p=all.length?Math.round(count/all.length*100):0;card.style.setProperty('--domain-progress',p+'%')})}
})();