(function(){
const chapters=window.AWS_BEGINNER_COURSE||[];
const PROGRESS='aws-beginner-course-progress-v1',CURRENT='aws-beginner-course-current-v1',QUIZ='aws-beginner-course-quiz-v1';
const $=id=>document.getElementById(id); const safeRead=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch(e){return f}};
let completed=new Set(safeRead(PROGRESS,[])),quiz=safeRead(QUIZ,{}),flat=[],current=Number(localStorage.getItem(CURRENT)||0),collapsed=false;
chapters.forEach((chapter,ci)=>chapter.lessons.forEach((lesson,li)=>flat.push({chapter,lesson,ci,li,id:`c${ci}-l${li}`})));
current=Math.max(0,Math.min(current,flat.length-1));
function save(){localStorage.setItem(PROGRESS,JSON.stringify([...completed]));localStorage.setItem(CURRENT,String(current));localStorage.setItem(QUIZ,JSON.stringify(quiz));}
function progress(){const pct=flat.length?Math.round(completed.size/flat.length*100):0;$('totalLessons').textContent=flat.length;$('completedLessons').textContent=completed.size;$('courseProgressPct').textContent=pct+'%';$('courseProgressRing').style.setProperty('--progress',pct+'%');$('curriculumDone').textContent=`${completed.size} complete`;$('curriculumPercent').textContent=pct+'%';$('curriculumBar').style.width=pct+'%';$('resumeCourse').textContent=completed.size?'Continue learning':'Start learning';}
function renderCurriculum(query=''){const q=query.trim().toLowerCase();const root=$('courseCurriculum');root.innerHTML='';let count=0;chapters.forEach((chapter,ci)=>{const visible=chapter.lessons.map((lesson,li)=>({lesson,li,show:!q||(chapter.title+' '+chapter.subtitle+' '+lesson.title+' '+lesson.lead).toLowerCase().includes(q)}));if(!visible.some(x=>x.show))return;count++;const section=document.createElement('section');const open=!collapsed&&(q||ci===flat[current].ci);section.className='chapter-item '+(open?'open':'');const done=chapter.lessons.filter((_,li)=>completed.has(`c${ci}-l${li}`)).length;section.innerHTML=`<button class="chapter-toggle" type="button"><span class="chapter-number">${ci+1}</span><span><b>${chapter.title}</b><small>${done}/${chapter.lessons.length} complete · ${chapter.subtitle}</small></span><i>›</i></button><div class="chapter-lessons"></div>`;const list=section.querySelector('.chapter-lessons');visible.forEach(({lesson,li,show})=>{if(!show)return;const idx=flat.findIndex(x=>x.ci===ci&&x.li===li),id=`c${ci}-l${li}`;const b=document.createElement('button');b.type='button';b.className='chapter-lesson '+(idx===current?'active ':'')+(completed.has(id)?'complete':'');b.innerHTML=`<span class="lesson-check">✓</span><span><b>${lesson.title}</b><small>${lesson.duration} min</small></span>`;b.onclick=()=>{current=idx;save();renderLesson();renderCurriculum($('courseSearch').value)};list.appendChild(b)});section.querySelector('.chapter-toggle').onclick=()=>section.classList.toggle('open');root.appendChild(section)});if(!count)root.innerHTML='<div class="course-empty">No beginner lesson matches this search.</div>';}
function renderLesson(){const item=flat[current],l=item.lesson,c=item.chapter,id=item.id;$('readerSection').textContent=`Chapter ${item.ci+1} of ${chapters.length}`;$('readerDuration').textContent=`${l.duration} min`;$('readerCategory').textContent=c.title;$('readerTitle').textContent=l.title;$('readerLead').textContent=l.lead;$('plainExplanation').textContent=l.plain;$('lessonAnalogy').textContent=l.analogy;$('conceptFlow').innerHTML=l.flow.map((x,i)=>`<div class="flow-node"><span>${i+1}</span><b>${x}</b></div>`).join('<i>→</i>');$('lessonPoints').innerHTML=l.points.map(x=>`<div><span>✓</span><p>${x}</p></div>`).join('');$('lessonExample').textContent=l.example;$('termGrid').innerHTML=l.terms.map(([term,meaning])=>`<article><b>${term}</b><p>${meaning}</p></article>`).join('');$('readerPosition').textContent=`Lesson ${current+1} of ${flat.length}`;
const understood=completed.has(id);$('markLesson').classList.toggle('complete',understood);$('markLesson').querySelector('b').textContent=understood?'Understood':'Mark understood';$('prevLesson').disabled=current===0;$('nextLesson').disabled=current===flat.length-1;$('nextLesson').textContent=current===flat.length-1?'Course complete':'Next lesson →';
const lab=$('courseLabCard');if(l.lab){lab.hidden=false;$('courseLabTitle').textContent=`Practice: ${l.title}`;$('courseLabLink').href=l.lab}else lab.hidden=true;
$('checkQuestion').textContent=l.check.q;$('checkOptions').innerHTML='';$('checkFeedback').className='check-feedback';$('checkFeedback').textContent='';l.check.options.forEach((o,i)=>{const b=document.createElement('button');b.type='button';b.className='check-option';b.innerHTML=`<span>${String.fromCharCode(65+i)}</span><b>${o}</b>`;b.onclick=()=>answer(i);$('checkOptions').appendChild(b)});if(quiz[id]!==undefined)paintQuiz(quiz[id]);window.scrollTo({top:0,behavior:'smooth'});}
function answer(choice){const id=flat[current].id;quiz[id]=choice;save();paintQuiz(choice)}
function paintQuiz(choice){const l=flat[current].lesson;[...$('checkOptions').children].forEach((b,i)=>{b.disabled=true;b.classList.toggle('selected',i===choice);b.classList.toggle('correct',i===l.check.correct);b.classList.toggle('wrong',i===choice&&i!==l.check.correct)});const ok=choice===l.check.correct;$('checkFeedback').className='check-feedback show '+(ok?'good':'retry');$('checkFeedback').innerHTML=`<b>${ok?'Correct.':'Not yet.'}</b> ${l.check.explain}`;}
$('markLesson').onclick=()=>{const id=flat[current].id;completed.has(id)?completed.delete(id):completed.add(id);save();progress();renderLesson();renderCurriculum($('courseSearch').value)};
$('prevLesson').onclick=()=>{if(current>0){current--;save();renderLesson();renderCurriculum($('courseSearch').value)}};
$('nextLesson').onclick=()=>{if(current<flat.length-1){completed.add(flat[current].id);current++;save();progress();renderLesson();renderCurriculum($('courseSearch').value)}};
$('resumeCourse').onclick=()=>document.getElementById('courseWorkspace').scrollIntoView({behavior:'smooth'});
$('courseSearch').oninput=e=>renderCurriculum(e.target.value);
$('collapseAll').onclick=()=>{collapsed=!collapsed;$('collapseAll').textContent=collapsed?'+':'−';document.querySelectorAll('.chapter-item').forEach(x=>x.classList.toggle('open',!collapsed))};
const global=$('globalSearch');if(global)global.oninput=e=>{$('courseSearch').value=e.target.value;renderCurriculum(e.target.value)};
progress();renderCurriculum();renderLesson();
})();